server:
  port: ${port:0}

spring:
  application:
    name: users-ws
---
spring:
  profiles: dev
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users-ws
      auto-index-creation: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  rabbitmq:
    host: localhost
    port: 5672
    username: b_yousefi
    password: b_yousefi

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: mappings

logging:
  file:
    name: 'users-ws.log'
---
spring:
  profiles: test
  data:
    mongodb:
      host: localhost
      port: 0
      database: users-ws-test
      auto-index-creation: true
  autoconfigure:
    exclude : org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
eureka:
  client:
    enabled: false

#springdoc:
#  api-docs:
#    path: /api-docs
#  swagger-ui:
#    path: /swagger-ui-custom.html
#  version: 1